version: 2
updates:
  # Manage pip dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  # Manage dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
